N_particles = 2000
N_statedims = 4

PARTICLE_FOLLOW_MEASUREMENT_SPEED = 0.1
PARTICLE_NOISE = 5.0
PARTICLE_REDISTRIBUTION_FRACTION = 0.01

# parameters for visualization
VIS_PARTICLE_RADIUS = 2
VIS_PARTICLE_COLOR = (0, 0, 255) # red